Controllers/CarritoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using ProyectoFinal_CarritoCompras.Models;
using ProyectoFinal_CarritoCompras.Datos;
using ProyectoFinal_CarritoCompras.Extensions;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace ProyectoFinal_CarritoCompras.Controllers
{
    public class CarritoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CarritoController( ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var categorias = _context.Categorias.ToList();
            var marcas = _context.Marcas.ToList();
            var carrito = HttpContext.Session.GetObjectFromJson<List<CarroCompra>>("Carro") ?? new List<CarroCompra>();
            var viewModel = new VistaDetalleVentacs { Categorias = categorias, Marcas = marcas, CarroCompra = carrito };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult BuscarProductos(string tipoBusqueda, int id)
        {
            IQueryable<Producto> productos = _context.Productos.Include(p => p.Categoria).Include(p => p.Marca);

            if (tipoBusqueda == "Categoria")
            {
                productos = productos.Where(p => p.IdCategoria == id);
            }
            else if (tipoBusqueda == "Marca")
            {
                productos = productos.Where(p => p.IdMarca == id);
            }

            var productosList = productos.ToList();
            var categorias = _context.Categorias.ToList();
            var marcas = _context.Marcas.ToList();
            var viewModel = new VistaDetalleVentacs
            {
                Categorias = categorias,
                Marcas = marcas,
                Producto = productosList,
                TipoBusqueda = tipoBusqueda
            };

            return View("Index", viewModel);
        }

        [Authorize]

        [HttpPost]
        public IActionResult AgregarAlCarro(int idProducto, int cantidad)
        {
            
                var producto = _context.Productos.Include(p => p.Categoria).Include(p => p.Marca).FirstOrDefault(p => p.IdProducto == idProducto);

                if (producto == null)
                {
                    return NotFound();
                }

                List<CarroCompra> carro = HttpContext.Session.GetObjectFromJson<List<CarroCompra>>("Carro") ?? new List<CarroCompra>();

                var itemEnCarro = carro.FirstOrDefault(c => c.Producto.IdProducto == idProducto);

                if (itemEnCarro == null)
                {
                    carro.Add(new CarroCompra { Producto = producto, Cantidad = cantidad });
                }
                else
                {
                    itemEnCarro.Cantidad += cantidad;
                }

                HttpContext.Session.SetObjectAsJson("Carro", carro);

                return RedirectToAction("Index");
           
        }

        [HttpPost]
        public IActionResult ActualizarCantidad(int idProducto, int cantidad)
        {
            List<CarroCompra> carro = HttpContext.Session.GetObjectFromJson<List<CarroCompra>>("Carro");

            if (carro != null)
            {
                var itemEnCarro = carro.FirstOrDefault(c => c.Producto.IdProducto == idProducto);
                if (itemEnCarro != null)
                {
                    itemEnCarro.Cantidad = cantidad;
                    HttpContext.Session.SetObjectAsJson("Carro", carro);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EliminarDelCarro(int idProducto)
        {
            List<CarroCompra> carro = HttpContext.Session.GetObjectFromJson<List<CarroCompra>>("Carro");

            if (carro != null)
            {
                var itemEnCarro = carro.FirstOrDefault(c => c.Producto.IdProducto == idProducto);
                if (itemEnCarro != null)
                {
                    carro.Remove(itemEnCarro);
                    HttpContext.Session.SetObjectAsJson("Carro", carro);
                }
            }

            return RedirectToAction("Index");
        }

        [Authorize]

        [HttpPost]
        public IActionResult RealizarPago()
        {
            var carroItems = HttpContext.Session.GetObjectFromJson<List<CarroCompra>>("Carro") ?? new List<CarroCompra>();
            HttpContext.Session.Remove("Carro");
            return View("ConfirmacionCompra", carroItems);
        }

        [Authorize]

        [HttpPost]
        public IActionResult ConfirmarCompra()
        {
            var carroItems = HttpContext.Session.GetObjectFromJson<List<CarroCompra>>("Carro") ?? new List<CarroCompra>();

            if (carroItems.Count == 0)
            {
                return RedirectToAction("Index");
            }

            var nuevaVenta = new DetalleVenta
            {
                Subtotal = carroItems.Sum(item => item.Producto.Precio * item.Cantidad),
                Total = carroItems.Sum(item => item.Producto.Precio * item.Cantidad) 
            };


            foreach (var item in carroItems)
            {
                var detalle = new CarroCompra
                {
                    IdProducto = item.Producto.IdProducto,
                    Cantidad = item.Cantidad,
                    Subtotal = item.Producto.Precio * item.Cantidad
                };
            }

            _context.SaveChanges();

            HttpContext.Session.Remove("Carro");

            return RedirectToAction("CompraConfirmada");
        }

        public IActionResult ObtenerOpciones(string tipoBusqueda)
        {
            List<SelectListItem> opciones = new List<SelectListItem>();

            if (tipoBusqueda == "Categoria")
            {
                var categorias = _context.Categorias.ToList();
                opciones = categorias.Select(c => new SelectListItem
                {
                    Value = c.IdCategoria.ToString(),
                    Text = c.NombreCategoria
                }).ToList();
            }
            else if (tipoBusqueda == "Marca")
            {
                var marcas = _context.Marcas.ToList();
                opciones = marcas.Select(m => new SelectListItem
                {
                    Value = m.IdMarca.ToString(),
                    Text = m.NombreMarca
                }).ToList();
            }

            return Json(opciones);
        }

        public IActionResult CompraConfirmada()
        {
            ViewBag.MensajeConfirmacion = "Compra Realizada con éxito";
            return View();
        }


    }
}

Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoFinal_CarritoCompras.Datos;
using ProyectoFinal_CarritoCompras.Models;
using System.Threading.Tasks;

namespace ProyectoFinal_CarritoCompras.Controllers
{
    public class ProductoController : Controller
    
    {
        private readonly ApplicationDbContext _context;

        public ProductoController (ApplicationDbContext context)

        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var productos = await _context.Productos
                .Include(p => p.Categoria)
                .Include(p => p.Marca)
                .ToListAsync();

            return View(productos);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoFinal_CarritoCompras</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 navbar-morado">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" alt="ProyectoFinal_CarritoCompras" style="height: 200px; width: auto;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between flex-row-reverse">
                    <partial name="_LoginPartial" />
                    <div class="nav-item carrito-container">
                        <a class="nav-link text-light" asp-area="" asp-controller="Carrito" asp-action="Index">
                            <img src="~/images/imgcarro.png" alt="ProyectoFinal_CarritoCompras" class="carrito-img" />
                        </a>
                    </div>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light nav-link-grande" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProyectoFinal_CarritoCompras - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>